#!/bin/bash

echo "Compiling logger"
cd logger
cargo $@
rc=$?;
cd ../
if [[ $rc != 0 ]]; then exit $rc; fi

echo "Compiling data_store"
cd data_store 
cargo $@
rc=$?;
cd ../
if [[ $rc != 0 ]]; then exit $rc; fi

echo "Compiling server"
cd server
cargo $@
rc=$?;
cd ../
if [[ $rc != 0 ]]; then exit $rc; fi

echo "Compiling shared"
cd shared
cargo $@
rc=$?;
cd ../
if [[ $rc != 0 ]]; then exit $rc; fi

echo "Compiling tcp_connector"
cd tcp_connector
cargo $@
rc=$?;
cd ../
if [[ $rc != 0 ]]; then exit $rc; fi

echo "Done"
